image: dmanthing/multi-python:latest

stages:
  - test
  - release

before_script:
  - pip install hatch

test-job:
  stage: test
  script:
    - hatch run test:test -x

release-job:
  script:
    - hatch build -t wheel
    - echo $MOSAIK_PYPI_USER
    - hatch publish -u $MOSAIK_PYPI_USER -a $MOSAIK_PYPI_PASSWORD
  stage: release
  only:
    - tags
