include:
  - project: mosaik/templates/ci-cd-templates
    file: main-only.yml
    inputs:
      package: mosaik-pandapower-2
      main_branch: main
      typecheck: always
      test_pythons: ["3.10", "3.11", "3.12", "3.13"]
