image: python:3.11

stages:
  - test
  - release

before_script:
  - pip install hatch

test-3-11-job:
  image: python:3.11
  stage: test
  script:
    - hatch run +py=3.11 test:test -x

test-3-9-job:
  image: python:3.9
  stage: test
  script:
    - hatch run +py=3.9 test:test -x

release-job:
  script:
    - hatch build
    - echo $MOSAIK_PYPI_USER
    - hatch publish -u $MOSAIK_PYPI_USER -a $MOSAIK_PYPI_PASSWORD
  stage: release
  only:
    - tags
