image: python:3.10

stages:
    -   release

.install-poetry: &install-hatch
  before_script:
    - pip install hatch
    - echo $MOSAIK_PYPI_USER

release-job:
  <<: *install-hatch
  script:
    - hatch build -t wheel
    - hatch publish -r test -u $MOSAIK_PYPI_USER -a $MOSAIK_TEST_PYPI_TOKEN
  stage: release
  only:
    - tags
