# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: format
        name: Run Formatter
        entry: uvx ruff format
        language: system
        types: [python]
      - id: lint
        name: Run Linter
        entry: uvx ruff check
        language: system
        types: [python]
      - id: test
        name: Run test suite
        language: system
        entry: uv run pytest -x
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [pre-push]
default_install_hook_types:
  - pre-commit
  - pre-push
